package org.example.passport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5.fuse.jdk11-800012
 * 2020-01-02T19:00:20.873+05:30
 * Generated source version: 3.3.5.fuse.jdk11-800012
 *
 */
@WebService(targetNamespace = "http://www.example.org/Passport/", name = "Passport")
@XmlSeeAlso({ObjectFactory.class})
public interface Passport {

    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/Passport/NewOperation")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.example.org/Passport/", className = "org.example.passport.NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.example.org/Passport/", className = "org.example.passport.NewOperationResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.lang.String newOperation(

        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
