package org.example.passport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5.fuse.jdk11-800012
 * 2020-01-02T19:00:20.904+05:30
 * Generated source version: 3.3.5.fuse.jdk11-800012
 *
 */
@WebServiceClient(name = "Passport",
                  wsdlLocation = "file:/D:/ESB/TM_eKYC/src/main/resources/Passport.wsdl",
                  targetNamespace = "http://www.example.org/Passport/")
public class Passport_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/Passport/", "Passport");
    public final static QName PassportSOAP = new QName("http://www.example.org/Passport/", "PassportSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/ESB/TM_eKYC/src/main/resources/Passport.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Passport_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/ESB/TM_eKYC/src/main/resources/Passport.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Passport_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Passport_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Passport_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Passport_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Passport_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Passport_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Passport
     */
    @WebEndpoint(name = "PassportSOAP")
    public Passport getPassportSOAP() {
        return super.getPort(PassportSOAP, Passport.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Passport
     */
    @WebEndpoint(name = "PassportSOAP")
    public Passport getPassportSOAP(WebServiceFeature... features) {
        return super.getPort(PassportSOAP, Passport.class, features);
    }

}
