package passport.tml.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5.fuse.jdk11-800012
 * 2020-01-03T10:50:49.759+05:30
 * Generated source version: 3.3.5.fuse.jdk11-800012
 *
 */
@WebService(targetNamespace = "http://service.TML.passport/", name = "dataPortWS")
@XmlSeeAlso({ObjectFactory.class})
public interface DataPortWS {

    @WebMethod(operationName = "OTPRequest")
    @RequestWrapper(localName = "OTPRequest", targetNamespace = "http://service.TML.passport/", className = "passport.tml.service.OTPRequestObject")
    @ResponseWrapper(localName = "OTPResponse", targetNamespace = "http://service.TML.passport/", className = "passport.tml.service.OTPResponseObject")
    public void otpRequest(

        @WebParam(name = "docType", targetNamespace = "")
        java.lang.String docType,
        @WebParam(name = "consent", targetNamespace = "")
        java.lang.String consent,
        @WebParam(name = "fileNo", targetNamespace = "")
        java.lang.String fileNo,
        @WebParam(name = "dob", targetNamespace = "")
        java.lang.String dob,
        @WebParam(name = "passportNo", targetNamespace = "")
        java.lang.String passportNo,
        @WebParam(name = "doi", targetNamespace = "")
        java.lang.String doi,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> statusCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> requestId,
        @WebParam(mode = WebParam.Mode.OUT, name = "result", targetNamespace = "")
        javax.xml.ws.Holder<ResultObject> result
    );
}
