package passport.tml.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5.fuse.jdk11-800012
 * 2020-01-03T10:50:49.790+05:30
 * Generated source version: 3.3.5.fuse.jdk11-800012
 *
 */
@WebServiceClient(name = "dataPortWS",
                  wsdlLocation = "file:/D:/ESB/TM_eKYC/src/main/resources/Passport.wsdl",
                  targetNamespace = "http://service.TML.passport/")
public class DataPortWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.TML.passport/", "dataPortWS");
    public final static QName DataPortwsPort = new QName("http://service.TML.passport/", "dataPortwsPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/ESB/TM_eKYC/src/main/resources/Passport.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DataPortWS_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/ESB/TM_eKYC/src/main/resources/Passport.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DataPortWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DataPortWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataPortWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DataPortWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DataPortWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DataPortWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DataPortWS
     */
    @WebEndpoint(name = "dataPortwsPort")
    public DataPortWS getDataPortwsPort() {
        return super.getPort(DataPortwsPort, DataPortWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataPortWS
     */
    @WebEndpoint(name = "dataPortwsPort")
    public DataPortWS getDataPortwsPort(WebServiceFeature... features) {
        return super.getPort(DataPortwsPort, DataPortWS.class, features);
    }

}
